export const FEATURE_TYPES = {
  FETCH_FEATURES_START: "features/FETCH_FEATURES_START",
  FETCH_FEATURES_SUCCESS: "features/FETCH_FEATURES_SUCCESS",
  FETCH_FEATURES_FAILED: "features/FETCH_FEATURES_FAILED",
};
